Repository thoth-station/jupyter-notebook, pull requests merged in 2018-11, with the labels that each got.

#208 Automatic update of dependency thoth-storages from 0.7.1 to 0.7.2
  requirements.txt
Labels: bot

#209 Automatic update of dependency thoth-adviser from 0.1.1 to 0.3.0
  requirements.txt
Labels: bot

#210 Automatic update of dependency plotly from 3.3.0 to 3.4.0
  requirements.txt
Labels: bot

#211 Automatic update of dependency numpy from 1.15.3 to 1.15.4
  requirements.txt
Labels: bot

#212 Automatic update of dependency thoth-common from 0.3.16 to 0.4.0
  requirements.txt
Labels: bot

#214 Automatic update of dependency dash from 0.28.5 to 0.28.7
  requirements.txt
Labels: bot

#215 Automatic update of dependency dash from 0.28.7 to 0.29.0
  requirements.txt
Labels: bot

#216 Automatic update of dependency thoth-storages from 0.7.2 to 0.7.3
  requirements.txt
Labels: bot

#218 Automatic update of dependency thoth-storages from 0.7.3 to 0.7.4
  requirements.txt
Labels: bot

#219 Automatic update of dependency thoth-storages from 0.7.4 to 0.7.5
  requirements.txt
Labels: bot

#220 Automatic update of dependency thoth-storages from 0.7.5 to 0.7.6
  requirements.txt
Labels: bot

#217 Add jupyter notebook extensions
  requirements.in
  requirements.txt
Labels: size/M

#221 Enable default set of nbextensions
  .s2i/bin/assemble
Labels: approved, size/XS
